name: Hypermod
description: A GitHub action to perform transformations triggered via the Hypermod App
runs:
  using: "node20"
  main: "index.js"
inputs:
  data:
    description: "Events dispatched from the Hypermod app as JSON"
    required: true
outputs:
  pullRequestNumbers:
    description: "The pull request number that was created or updated (comma separated)"
branding:
  icon: "star"
  color: "black"
