name: Hypermod
description: A GitHub action to perform transformations triggered via the Hypermod App
runs:
  using: "node20"
  main: "dist/index.js"
inputs:
  eventType:
    description: "Event type dispatched from the Hypermod app"
    type: choice
    required: true
    options:
      - transform
      - check
  transformIds:
    description: "Transform Ids to run (comma separated)"
    type: string
    required: true
  directories:
    description: "Directories Ids to run (comma separated)"
    type: string
    required: true
outputs:
  pullRequestNumbers:
    description: "The pull request number that was created or updated (comma separated)"
branding:
  icon: "star"
  color: "black"
