name: Hypermod
description: A GitHub action to perform batch transformations triggered via the Hypermod App
runs:
  using: "node20"
  main: "dist/index.js"
inputs:
  deploymentId:
    description: "The ID of the deployment to run"
    type: string
    required: true
  deploymentKey:
    description: "The deployment secret key which authorizes the action to run the deployment"
    type: string
    required: true
outputs:
  pullRequestNumbers:
    description: "The pull request number(s) created or updated (comma separated)"
branding:
  icon: "star"
  color: "black"
