name: Hypermod
description: A GitHub action to perform transformations triggered via the Hypermod App
runs:
  using: "node18"
  main: "dist/index.js"
inputs:
  eventType:
    description: 'Event type (CHECK or TRANSFORM)'
    required: true
  transformIds:
    description: 'ID for the transform process (comma separated)'
    required: false
  directories:
    description: 'Glob of directories for processing (comma separated)'
    required: false
outputs:
  pullRequestNumbers:
    description: 'The pull request number that was created or updated (comma separated)'
branding:
  icon: "star"
  color: "black"